application:    g-shared-contacts
version:        1
runtime:        php55
api_version:    1

handlers:
        - url: /favicon\.ico
          static_files: public/favicon.ico
          upload: public/favicon\.ico

        - url: /assets/(.*\.(htm$|html$|ttf$|css$|js$|png$|woff$))
          static_files: public/assets/\1
          upload: public/assets/(.*\.(htm$|ttf$|html$|css$|js$|png$|woff$))
          application_readable: true

        - url: /.*
          script: public/index.php

skip_files:
        - ^(.*/)?#.*#$
        - ^(.*/)?.*~$
        - ^(.*/)?.*\.py[co]$
        - ^(.*/)?.*/RCS/.*$
        - ^(.*/)?\.(?!env).*$
        - ^(.*/)?node_modules.*$
        - ^(.*/)?_ide_helper\.php$
        - ^(.*/)?\.DS_Store$

env_variables:
        GAE_SKIP_GCS_INIT: true